import React from 'react';
import Navigation from '../components/Navigation/Navigation';

const Contact = () => {
    return (
        <div>
            <Navigation/>
            <h1 className="h1-1"> Nous contacter </h1>

         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
         <h1> lorem ipsum dolor sit amet</h1>
        </div>
    );
};

export default Contact;